# Generated by Django 5.1a1 on 2024-11-06 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_title', models.CharField(max_length=100, verbose_name='Görev Başlığı')),
                ('Task_Description', models.TextField(verbose_name='Görev İçeriği')),
                ('Task_Status', models.TextField(choices=[('Not_Resolved', 'Tamamlanmadı'), ('Ongoing', 'Devam Ediyor'), ('Finished', 'Tamamlandı'), ('Pending', 'Beklemede'), ('Cancelled', 'İptal Edildi')], max_length=20, verbose_name='Son Durum')),
                ('Task_Created_at', models.DateField(auto_now_add=True)),
                ('Task_Updated_at', models.DateField(auto_now=True)),
                ('Task_due_date', models.DateTimeField(blank=True, null=True)),
                ('Task_Asigned_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
