# Generated by Django 5.1a1 on 2024-11-06 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Asigned_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Görev Atanan'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_Created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Görevin atandığı zaman'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_Updated_at',
            field=models.DateField(auto_now=True, verbose_name='Son güncelleme'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin Tarihi'),
        ),
    ]
