# Generated by Django 5.1a1 on 2024-11-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_task_task_asigned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task_due_date',
            new_name='Task_Due_Date',
        ),
        migrations.AddField(
            model_name='task',
            name='Task_Priority',
            field=models.CharField(choices=[('High', 'Yüksek'), ('Normal', 'Normal'), ('Low', 'Düşük')], default='-', max_length=10, verbose_name='Öncelik Düzeyi'),
            preserve_default=False,
        ),
    ]
