# Generated by Django 5.1a1 on 2024-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_rename_task_due_date_task_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Priority',
            field=models.CharField(choices=[('High', 'Yüksek'), ('Normal', 'Normal'), ('Low', 'Düşük')], default=('Normal', 'Normal'), max_length=10, verbose_name='Öncelik Düzeyi'),
        ),
    ]
