# Generated by Django 5.1a1 on 2024-11-06 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_alter_task_task_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Task_Asigned_at',
        ),
        migrations.AddField(
            model_name='task',
            name='Task_Asigned_at',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Görev Atanan'),
        ),
    ]
