# Generated by Django 5.1a1 on 2024-11-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Status',
            field=models.TextField(choices=[('Not_Resolved', 'Tamamlanmadı'), ('Ongoing', 'Devam Ediyor'), ('Finished', 'Tamamlandı'), ('Pending', 'Beklemede'), ('Cancelled', 'İptal Edildi')], default="('Not_Resolved', 'Tamamlanmadı')", max_length=20, verbose_name='Son Durum'),
        ),
    ]
