# Generated by Django 5.1a1 on 2024-11-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0010_alter_task_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task_Status',
            new_name='Task_status',
        ),
    ]
