# Generated by Django 5.1a1 on 2024-11-06 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0011_rename_task_status_task_task_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Asigned_at',
            field=models.ManyToManyField(to='auth.group', verbose_name='Görev Atanan Grup'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_status',
            field=models.CharField(choices=[('NotResolved', 'Tamamlanmadı'), ('Ongoing', 'Devam Ediyor'), ('Finished', 'Tamamlandı'), ('Pending', 'Beklemede'), ('Cancelled', 'İptal Edildi')], default='NotResolved', max_length=20, verbose_name='Son Durum'),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subtask_title', models.CharField(max_length=100, verbose_name='Alt Görev Başlığı')),
                ('Subtask_Description', models.TextField(verbose_name='Alt Görev İçeriği')),
                ('Subtask_status', models.CharField(choices=[('NotResolved', 'Tamamlanmadı'), ('Ongoing', 'Devam Ediyor'), ('Finished', 'Tamamlandı')], default='NotResolved', max_length=20, verbose_name='Durum')),
                ('Subtask_due_date', models.DateField(blank=True, null=True, verbose_name='Termin Tarihi')),
                ('Subtask_Priority', models.CharField(choices=[('High', 'Yüksek'), ('Normal', 'Normal'), ('Low', 'Düşük')], default='Normal', max_length=10, verbose_name='Öncelik Düzeyi')),
                ('Task_Created_at', models.DateField(auto_now_add=True, verbose_name='Görevin atandığı zaman')),
                ('Task_Updated_at', models.DateField(auto_now=True, verbose_name='Son güncelleme')),
                ('Parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Tasks.task', verbose_name='Ana Görev')),
                ('Subtask_Asigned_at', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Görev Atanan')),
            ],
        ),
    ]
