# Generated by Django 5.1a1 on 2024-11-06 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0012_alter_task_task_asigned_at_alter_task_task_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Asigned_at',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Görev Atanan Grup'),
        ),
    ]
