# Generated by Django 5.1a1 on 2024-11-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0013_alter_task_task_asigned_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='Task_Created_at',
            new_name='Subtask_Created_at',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='Task_Updated_at',
            new_name='Subtask_Updated_at',
        ),
    ]
