# Generated by Django 5.1a1 on 2024-11-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0014_rename_task_created_at_subtask_subtask_created_at_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Asigned_at',
            field=models.ManyToManyField(to='auth.group', verbose_name='Görev Atanan Grup'),
        ),
    ]
