# Generated by Django 5.1a1 on 2024-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0016_alter_subtask_subtask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IECEE_tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Test Konusu')),
                ('EUT_component', models.CharField(max_length=100, verbose_name='Test Edilecek Komponent/Parça/Makine')),
                ('Test_type', models.CharField(choices=[('Malzeme', 'Malzeme'), ('Elektriksel', 'Elektriksel')], max_length=30, verbose_name='Test Türü')),
                ('Description', models.TextField(verbose_name='Açıklama')),
                ('Test_result', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK'), ('Kararsız', 'Kararsız')], max_length=30, verbose_name='Test Sonucu')),
                ('Test_link', models.CharField(help_text='Test dosyalarının bulunduğu klasör linki', max_length=300, verbose_name='Test Linki')),
                ('Comments', models.TextField(verbose_name='Gözlemler/Yorumlar')),
                ('Test_create_date', models.DateField(auto_now_add=True)),
                ('Test_update_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
