# Generated by Django 5.1a1 on 2024-12-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0018_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Order',
            field=models.FileField(default='-', upload_to='orders/', verbose_name='Teklif'),
        ),
    ]
