# Generated by Django 5.1.4 on 2024-12-30 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0019_account_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='E_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('Last_Update', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('Topic', models.CharField(max_length=100, verbose_name='Konu')),
                ('Content', models.TextField(verbose_name='İçerik')),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='lab/', verbose_name='Fotoğraf')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='lab/', verbose_name='Fotoğraf')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='lab/', verbose_name='Fotoğraf')),
                ('Photo4', models.ImageField(blank=True, null=True, upload_to='lab/', verbose_name='Fotoğraf')),
                ('Photo5', models.ImageField(blank=True, null=True, upload_to='lab/', verbose_name='Fotoğraf')),
                ('Report', models.FileField(blank=True, null=True, upload_to='lab/', verbose_name='Test Verileri')),
                ('Priority', models.CharField(choices=[('High', 'Yüksek'), ('Normal', 'Normal'), ('Low', 'Düşük')], default='Normal', max_length=100, verbose_name='Öncelik')),
                ('Status', models.CharField(choices=[('NotResolved', 'Tamamlanmadı'), ('Ongoing', 'Devam Ediyor'), ('Finished', 'Tamamlandı'), ('Pending', 'Beklemede'), ('Cancelled', 'İptal Edildi')], default='NotResolved', max_length=100, verbose_name='Durum')),
                ('Requested_to', models.ManyToManyField(related_name='e_lab_Requested_to', to=settings.AUTH_USER_MODEL, verbose_name='Atanan')),
                ('Requester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='e_lab_Requester', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
        ),
        migrations.CreateModel(
            name='EMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=100, verbose_name='Test')),
                ('Number', models.CharField(max_length=100, verbose_name='Test Numarası')),
                ('Machine', models.CharField(max_length=100, verbose_name='Test Makinesi')),
                ('Delivery_Date', models.DateField(verbose_name='Teslim Tarihi')),
                ('Update_Date', models.DateField(auto_now=True, verbose_name='Son Güncelleme')),
                ('Status', models.CharField(max_length=100, verbose_name='Durum')),
                ('Result', models.CharField(choices=[('Pass', 'Geçti'), ('Fail', 'Başarısız')], max_length=100, verbose_name='Sonuç')),
                ('Requester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='emc_Requester', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
        ),
        migrations.CreateModel(
            name='EMC_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conducted_Emission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conducted Emission')),
                ('Flicker', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flicker')),
                ('Discharge', models.CharField(blank=True, max_length=100, null=True, verbose_name='Electrostatic Discharge')),
                ('Harmonic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Harmonic')),
                ('Burst', models.CharField(blank=True, max_length=100, null=True, verbose_name='Burst')),
                ('Surge', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surge')),
                ('Conducted_Disturbance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conducted Disturbance')),
                ('Voltage_Dips', models.CharField(blank=True, max_length=100, null=True, verbose_name='Voltage Dips')),
                ('Disturbance_Power', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disturbance Power')),
                ('Radiated_Impunity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Radiated Immunity')),
                ('Discontinious_Disturbance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discontinious Disturbance')),
                ('EMC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tasks.emc', verbose_name='EMC Testi')),
            ],
        ),
        migrations.DeleteModel(
            name='IECEE_tests',
        ),
        migrations.AlterField(
            model_name='account',
            name='Order',
            field=models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Teklif'),
        ),
    ]
