# Generated by Django 5.1.4 on 2024-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0020_e_lab_emc_emc_test_delete_iecee_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emc',
            name='Test_link',
            field=models.URLField(blank=True, null=True, verbose_name='Test Linki'),
        ),
    ]
