# Generated by Django 5.1.4 on 2024-12-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0021_emc_test_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emc',
            name='Status',
            field=models.CharField(choices=[('NotResolved', 'Tamamlanmadı'), ('Ongoing', 'Devam Ediyor'), ('Finished', 'Tamamlandı'), ('Pending', 'Beklemede'), ('Cancelled', 'İptal Edildi')], default='NotResolved', max_length=100, verbose_name='Durum'),
        ),
    ]
