# Generated by Django 5.1.4 on 2024-12-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0023_alter_emc_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emc',
            name='Delivery_Date',
            field=models.DateField(auto_now_add=True, verbose_name='Teslim Tarihi'),
        ),
    ]
