# Generated by Django 5.1.4 on 2024-12-30 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0024_alter_emc_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emc_test',
            name='EMC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.emc', verbose_name='EMC Testi'),
        ),
    ]
