# Generated by Django 5.1.4 on 2024-12-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0026_emc_notes_eut_hardware_eut_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='emc',
            name='EUT_Description',
            field=models.FileField(blank=True, null=True, upload_to='emc/', verbose_name='EUT File'),
        ),
        migrations.AlterField(
            model_name='emc',
            name='Test_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Test Linki'),
        ),
    ]
