# Generated by Django 5.1.4 on 2024-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0027_emc_eut_description_alter_emc_test_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eut_hardware',
            name='Twinjet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Twinjet'),
        ),
    ]
