# Generated by Django 5.1.4 on 2025-01-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0028_alter_eut_hardware_twinjet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Order',
            field=models.FileField(blank=True, null=True, upload_to='orders/<django.db.models.fields.CharField>', verbose_name='Teklif'),
        ),
        migrations.AlterField(
            model_name='e_lab',
            name='Photo1',
            field=models.ImageField(blank=True, null=True, upload_to='lab/<django.db.models.fields.CharField>', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='e_lab',
            name='Photo2',
            field=models.ImageField(blank=True, null=True, upload_to='lab/<django.db.models.fields.CharField>', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='e_lab',
            name='Photo3',
            field=models.ImageField(blank=True, null=True, upload_to='lab/<django.db.models.fields.CharField>', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='e_lab',
            name='Photo4',
            field=models.ImageField(blank=True, null=True, upload_to='lab/<django.db.models.fields.CharField>', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='e_lab',
            name='Photo5',
            field=models.ImageField(blank=True, null=True, upload_to='lab/<django.db.models.fields.CharField>', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='e_lab',
            name='Report',
            field=models.FileField(blank=True, null=True, upload_to='lab/<django.db.models.fields.CharField>', verbose_name='Test Verileri'),
        ),
    ]
