# Generated by Django 5.1.4 on 2025-01-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0029_alter_account_order_alter_e_lab_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Order',
            field=models.FileField(blank=True, null=True, upload_to='orders/None', verbose_name='Teklif'),
        ),
    ]
