# Generated by Django 5.1.4 on 2025-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0031_alter_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Order',
            field=models.FileField(blank=True, null=True, upload_to='orders/__str__', verbose_name='Teklif'),
        ),
    ]
