# Generated by Django 5.1.4 on 2025-01-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0032_alter_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Order',
            field=models.FileField(blank=True, null=True, upload_to='orders/<bound method CharField.formfield of <django.db.models.fields.CharField>>', verbose_name='Teklif'),
        ),
    ]
