# Generated by Django 5.1.4 on 2025-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0033_alter_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Order',
            field=models.FileField(blank=True, null=True, upload_to='orders/bound-method-fieldvalue_from_object-of-djangodbmodelsfieldscharfield', verbose_name='Teklif'),
        ),
    ]
