# Generated by Django 5.1.4 on 2025-01-02 12:54

import Tasks.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0034_alter_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Order',
            field=models.FileField(blank=True, null=True, upload_to=Tasks.utils.order_upload_to, verbose_name='Teklif'),
        ),
    ]
