# Generated by Django 5.1.4 on 2025-01-04 11:31

import Tasks.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0035_alter_account_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_lab',
            name='Photo1',
        ),
        migrations.RemoveField(
            model_name='e_lab',
            name='Photo2',
        ),
        migrations.RemoveField(
            model_name='e_lab',
            name='Photo3',
        ),
        migrations.RemoveField(
            model_name='e_lab',
            name='Photo4',
        ),
        migrations.RemoveField(
            model_name='e_lab',
            name='Photo5',
        ),
        migrations.RemoveField(
            model_name='e_lab',
            name='Report',
        ),
        migrations.AddField(
            model_name='e_lab',
            name='Test_Files',
            field=models.FileField(blank=True, null=True, upload_to=Tasks.utils.e_lab_upload_to, verbose_name='Test Dosyaları'),
        ),
        migrations.AlterField(
            model_name='emc',
            name='EUT_Description',
            field=models.FileField(blank=True, null=True, upload_to=Tasks.utils.emc_upload_to, verbose_name='EUT File'),
        ),
    ]
