# Generated by Django 5.1.4 on 2025-01-11 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0036_remove_e_lab_photo1_remove_e_lab_photo2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_lab',
            name='Requested_to',
        ),
        migrations.AddField(
            model_name='e_lab',
            name='Requested_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='e_lab_Requested_to', to=settings.AUTH_USER_MODEL, verbose_name='Atanan'),
        ),
    ]
