# Generated by Django 5.1.4 on 2025-01-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0039_alter_e_lab_priority_alter_e_lab_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_lab',
            name='Content',
            field=models.TextField(verbose_name='İçerik/Yorumlar'),
        ),
    ]
