# Generated by Django 5.1a1 on 2024-11-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_name', models.CharField(max_length=100, verbose_name='Object / part No.')),
                ('Manufacturer', models.CharField(max_length=150, verbose_name='Manufacturer/ trademark')),
                ('Model', models.CharField(max_length=120, verbose_name='Type/Model')),
                ('Technical_Data', models.TextField(verbose_name='Technical Data')),
                ('Standard', models.CharField(max_length=120, verbose_name='Standard')),
                ('Mark_of_Conformity', models.CharField(max_length=120, verbose_name='Mark(s) of Conformity')),
            ],
        ),
    ]
