# Generated by Django 5.1a1 on 2024-11-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
    ]
