# Generated by Django 5.1a1 on 2024-11-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0003_component_f_washer_dryer_lvd_component_f_washer_lvd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='F_Washer_Dryer_LVD',
            field=models.BooleanField(default=False, verbose_name='F washer dryer'),
        ),
        migrations.AlterField(
            model_name='component',
            name='F_Washer_LVD',
            field=models.BooleanField(default=False, verbose_name='F washer'),
        ),
        migrations.AlterField(
            model_name='component',
            name='N_Washer_LVD',
            field=models.BooleanField(default=False, verbose_name='N washer'),
        ),
        migrations.AlterField(
            model_name='component',
            name='T_Washer_Dryer_LVD',
            field=models.BooleanField(default=False, verbose_name='T washer dryer'),
        ),
        migrations.AlterField(
            model_name='component',
            name='T_Washer_LVD',
            field=models.BooleanField(default=False, verbose_name='T washer'),
        ),
    ]
