# Generated by Django 5.1a1 on 2024-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0004_alter_component_f_washer_dryer_lvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='SAP_code',
            field=models.CharField(default='-', max_length=80, verbose_name='SAP Code'),
        ),
    ]
