# Generated by Django 5.1a1 on 2024-11-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0006_alter_component_sap_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='SAP_code',
            field=models.CharField(default='0', max_length=80, verbose_name='SAP Code'),
        ),
    ]
