# Generated by Django 5.1a1 on 2024-11-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0008_component_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_request',
            name='guidebook',
            field=models.URLField(default='file:///C:/Users/gorkemk/PycharmProjects/Workflow%20Tracking%20Application/WorkFlowTrackingTool/guidebooks/Test-Requirements.pdf', max_length=400, verbose_name='guidebook.pdf'),
        ),
    ]
