# Generated by Django 5.1a1 on 2024-11-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0009_alter_component_request_guidebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_request',
            name='guidebook',
        ),
    ]
