# Generated by Django 5.1.3 on 2024-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0012_alter_component_request_r_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='Certificate_Expiry_Date',
            field=models.DateField(default='2022-05-04', verbose_name='Certificate Expiry Date'),
        ),
    ]
