# Generated by Django 5.1a1 on 2024-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0013_component_certificate_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_request',
            name='Pre_Series_Date',
            field=models.DateField(default='2022-05-04', verbose_name='Pre Serie Date'),
        ),
    ]
