# Generated by Django 5.1a1 on 2024-11-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0014_component_request_pre_series_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Certificate_Expiry_Date',
            field=models.DateField(verbose_name='Certificate Expiry Date'),
        ),
        migrations.AlterField(
            model_name='component_request',
            name='Pre_Series_Date',
            field=models.DateField(verbose_name='Pre Serie Date'),
        ),
    ]
