# Generated by Django 5.1a1 on 2024-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0016_alter_component_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Certificate_Expiry_Date',
            field=models.DateField(help_text='Enter data in format YYYY-MM-DD', verbose_name='Certificate Expiry Date'),
        ),
        migrations.AlterField(
            model_name='component_request',
            name='Pre_Series_Date',
            field=models.DateField(help_text='Enter data in format YYYY-MM-DD', verbose_name='Pre Serie Date'),
        ),
    ]
