# Generated by Django 5.1a1 on 2024-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0018_alter_component_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_request',
            name='R_Mark_of_Conformity',
        ),
        migrations.AddField(
            model_name='component',
            name='Test_Results_Link',
            field=models.CharField(default='Empty', max_length=1000, verbose_name='Test Reports & Certificate Link'),
        ),
        migrations.AddField(
            model_name='component_request',
            name='Test_Results_Link',
            field=models.CharField(default='Empty', max_length=1000, verbose_name='Test Reports & Certificate Link'),
        ),
    ]
