# Generated by Django 5.1a1 on 2024-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0020_alter_component_test_results_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Certificate_Expiry_Date',
            field=models.DateField(help_text='Hint : Enter date in format YYYY-MM-DD', verbose_name='Certificate Expiry Date'),
        ),
        migrations.AlterField(
            model_name='component_request',
            name='Pre_Series_Date',
            field=models.DateField(help_text='Hint : Enter date in format YYYY-MM-DD', verbose_name='Date of Pre Series'),
        ),
    ]
