# Generated by Django 5.1a1 on 2024-11-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0021_alter_component_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Certificate_Expiry_Date',
            field=models.DateField(verbose_name='Certificate Expiry Date'),
        ),
        migrations.AlterField(
            model_name='component_request',
            name='Test_Results_Link',
            field=models.CharField(help_text='Warning : Folder must be placed in the local network VBCARGE', max_length=1000, verbose_name='Test Reports & Certificate Link'),
        ),
    ]
