# Generated by Django 5.1a1 on 2024-11-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0023_alter_component_sap_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='Created_Date',
            field=models.DateField(default='2022-12-11', verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='component',
            name='Last_Update_Date',
            field=models.DateField(default='2022-12-11', verbose_name='Last Update'),
        ),
        migrations.AddField(
            model_name='component_request',
            name='R_Created_Date',
            field=models.DateField(default='2022-12-11', verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='component_request',
            name='R_Last_Update_Date',
            field=models.DateField(default='2022-12-11', verbose_name='Last Update'),
        ),
    ]
