# Generated by Django 5.1a1 on 2024-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0024_component_created_date_component_last_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Created_Date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='component',
            name='Last_Update_Date',
            field=models.DateField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='component_request',
            name='R_Created_Date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='component_request',
            name='R_Last_Update_Date',
            field=models.DateField(auto_now=True, verbose_name='Last Update'),
        ),
    ]
