# Generated by Django 5.1a1 on 2024-11-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVD_Management_System', '0025_alter_component_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_request',
            name='R_Priority',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=40, verbose_name='Priority'),
        ),
    ]
